ingress:
  enabled: true
  ingressClassName: "nginx" 
  path: "/"
  pathType: Prefix
  serviceName: "awesome-service" 
  servicePort: 8080
  annotations: 
  hosts: 
    - "example.co.jp" 
  tls:
    - secretName: "example-secret" 
      hosts:
        - example.co.jp 